import { requireUser, credentialsFromForm, AuthError } from '../_shared/auth.mjs';
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import { PDFDocument, rgb } from "https://esm.sh/pdf-lib@1.17.1";
import fontkit from "https://esm.sh/@pdf-lib/fontkit@1.1.1";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"content-type"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const REG="https://raw.githubusercontent.com/google/fonts/main/ofl/ptsans/PT_Sans-Web-Regular.ttf";
const BOLD="https://raw.githubusercontent.com/google/fonts/main/ofl/ptsans/PT_Sans-Web-Bold.ttf";
let fontsPromise:Promise<{r:Uint8Array,b:Uint8Array}>|null=null;
async function fonts(){if(!fontsPromise)fontsPromise=(async()=>{const [r,b]=await Promise.all([fetch(REG),fetch(BOLD)]);if(!r.ok||!b.ok)throw new Error("pdf_font_unavailable");return{r:new Uint8Array(await r.arrayBuffer()),b:new Uint8Array(await b.arrayBuffer())}})();return fontsPromise}
const rub=(n:number)=>new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(Number(n||0));
const date=(s:string)=>/^\d{4}-\d{2}-\d{2}$/.test(s||"")?`${s.slice(8,10)}.${s.slice(5,7)}.${s.slice(0,4)}`:String(s||"");
function wrap(font:any,text:string,size:number,w:number,max=5){const words=String(text||"").replace(/\s+/g," ").trim().split(" ").filter(Boolean),lines:string[]=[];let line="";for(const word0 of words){let parts=[word0];if(font.widthOfTextAtSize(word0,size)>w){parts=[];let p="";for(const c of word0){const t=p+c;if(p&&font.widthOfTextAtSize(t,size)>w){parts.push(p);p=c}else p=t}if(p)parts.push(p)}for(const word of parts){const t=line?`${line} ${word}`:word;if(!line||font.widthOfTextAtSize(t,size)<=w)line=t;else{lines.push(line);line=word;if(lines.length>=max)break}}if(lines.length>=max)break}if(line&&lines.length<max)lines.push(line);return lines.length?lines:[""]}

async function makePdf(exp:any[], projects:Map<string,any>){const f=await fonts(),pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const reg=await pdf.embedFont(f.r,{subset:true}),bold=await pdf.embedFont(f.b,{subset:true});pdf.setTitle("ADMA - расходы к компенсации");pdf.setAuthor("ADMA Finance");
const W=595.28,H=841.89,M=36,CW=W-M*2,DATE=64,PROJECT=135,DESC=225;const border=rgb(.88,.88,.9),muted=rgb(.42,.42,.46),text=rgb(.08,.08,.1),head=rgb(.95,.95,.97);let page:any,y=0;
const tableHead=()=>{const h=26,xs=[M,M+DATE,M+DATE+PROJECT,M+DATE+PROJECT+DESC,M+CW];page.drawRectangle({x:M,y:y-h,width:CW,height:h,color:head,borderColor:border,borderWidth:.7});for(let i=1;i<xs.length-1;i++)page.drawLine({start:{x:xs[i],y},end:{x:xs[i],y:y-h},thickness:.7,color:border});for(const [t,x] of [["Дата",M+6],["Объект",M+DATE+6],["Расход",M+DATE+PROJECT+6]] as any)page.drawText(t,{x,y:y-17,size:9,font:bold,color:text});const t="Сумма";page.drawText(t,{x:M+CW-6-bold.widthOfTextAtSize(t,9),y:y-17,size:9,font:bold,color:text});y-=h};
const newPage=(first=false)=>{page=pdf.addPage([W,H]);y=H-M;if(!first){page.drawText("ADMA · Расходы к компенсации",{x:M,y:y-2,size:10,font:bold,color:text});y-=24;tableHead()}};
newPage(true);page.drawText("ADMA",{x:M,y,size:12,font:bold,color:text});y-=30;page.drawText("Расходы к компенсации",{x:M,y,size:22,font:bold,color:text});y-=29;const total=exp.reduce((s,e)=>s+Number(e.amount||0),0);page.drawText(`Итого к возмещению: ${rub(total)}`,{x:M,y,size:14,font:bold,color:text});y-=19;page.drawText(`Расходов: ${exp.length}`,{x:M,y,size:10,font:reg,color:muted});y-=15;const generated=new Intl.DateTimeFormat("ru-RU",{timeZone:"Europe/Moscow",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date());page.drawText(`Сформировано: ${generated}`,{x:M,y,size:9,font:reg,color:muted});y-=24;tableHead();
let cur="",sub=0;const subtotal=()=>{if(!cur)return;const p=projects.get(cur),label=`Итого по объекту «${p?.name||"Без названия"}»: ${rub(sub)}`,ls=wrap(bold,label,9,CW-12,2),h=10+ls.length*11;if(y-h<M+32)newPage(false);page.drawRectangle({x:M,y:y-h,width:CW,height:h,color:rgb(.975,.975,.985),borderColor:border,borderWidth:.7});ls.forEach((l,i)=>page.drawText(l,{x:M+6,y:y-14-i*11,size:9,font:bold,color:text}));y-=h};
for(const e of exp){if(cur&&cur!==String(e.project_id)){subtotal();sub=0}cur=String(e.project_id);sub+=Number(e.amount||0);const p=projects.get(cur),pLines=wrap(reg,p?.name||"Без объекта",8.5,PROJECT-12,3);const parts=[e.supplier||e.category||"Расход"];if(e.supplier&&e.category)parts.push(e.category);if(e.comment)parts.push(e.comment);if(e.receipt_path)parts.push("Чек приложен");const dLines=wrap(reg,parts.join(" · "),8.5,DESC-12,4),lines=Math.max(1,pLines.length,dLines.length),rh=Math.max(30,10+lines*11);if(y-rh<M+32)newPage(false);const xs=[M,M+DATE,M+DATE+PROJECT,M+DATE+PROJECT+DESC,M+CW];page.drawRectangle({x:M,y:y-rh,width:CW,height:rh,borderColor:border,borderWidth:.7});for(let i=1;i<xs.length-1;i++)page.drawLine({start:{x:xs[i],y},end:{x:xs[i],y:y-rh},thickness:.7,color:border});page.drawText(date(e.expense_date),{x:M+6,y:y-17,size:8.5,font:reg,color:text});pLines.forEach((l,i)=>page.drawText(l,{x:M+DATE+6,y:y-17-i*11,size:8.5,font:reg,color:text}));dLines.forEach((l,i)=>page.drawText(l,{x:M+DATE+PROJECT+6,y:y-17-i*11,size:8.5,font:reg,color:text}));const a=rub(Number(e.amount||0));page.drawText(a,{x:M+CW-6-reg.widthOfTextAtSize(a,8.5),y:y-17,size:8.5,font:reg,color:text});y-=rh}subtotal();
if(y-52<M+32)newPage(false);y-=18;page.drawLine({start:{x:M,y},end:{x:M+CW,y},thickness:1.2,color:text});y-=23;const grand=`ИТОГО: ${rub(total)}`;page.drawText(grand,{x:M+CW-bold.widthOfTextAtSize(grand,13),y,size:13,font:bold,color:text});const pages=pdf.getPages();pages.forEach((p,i)=>{const s=`ADMA Finance · ${i+1} / ${pages.length}`;p.drawText(s,{x:M,y:18,size:7.5,font:reg,color:muted})});return pdf.save()}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);const token=Deno.env.get("TELEGRAM_BOT_TOKEN");try{const form=await req.formData();const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});const user=await requireUser(db,credentialsFromForm(form),token);
let selected:string[]=[];try{const raw=String(form.get("expense_ids")||"");if(raw)selected=[...new Set(JSON.parse(raw).map((x:any)=>String(x)).filter(Boolean))] as string[]}catch{return json({error:"invalid_expense_ids"},400)}if(selected.length>250)return json({error:"too_many_expenses"},400);
let allowed:string[]|null=null;if(user.role==="foreman"){const {data:m,error:me}=await db.from("project_members").select("project_id").eq("user_id",user.id);if(me)throw me;allowed=(m||[]).map((x:any)=>x.project_id)}
let q=db.from("expenses").select("id,project_id,amount,expense_date,category,supplier,comment,receipt_path").eq("paid_by","adma").eq("reimbursement_required",true).eq("reimbursed",false);if(allowed)q=allowed.length?q.in("project_id",allowed):q.eq("project_id","00000000-0000-0000-0000-000000000000");if(selected.length)q=q.in("id",selected);const {data:expenses,error:ee}=await q;if(ee)throw ee;if(!(expenses||[]).length)return json({error:"no_pending_expenses"},400);
const pids=[...new Set((expenses||[]).map((e:any)=>String(e.project_id)))];const {data:ps,error:pe}=await db.from("projects").select("id,name").in("id",pids);if(pe)throw pe;const pm=new Map<string,any>((ps||[]).map((p:any)=>[String(p.id),p]));const ordered=[...(expenses||[])].sort((a:any,b:any)=>String(pm.get(String(a.project_id))?.name||"").localeCompare(String(pm.get(String(b.project_id))?.name||""),"ru")||String(a.expense_date).localeCompare(String(b.expense_date)));const bytes=await makePdf(ordered,pm),stamp=new Date().toISOString().slice(0,10),path=`${user.id}/reimbursement-latest.pdf`;const {error:up}=await db.storage.from("exports").upload(path,bytes,{contentType:"application/pdf",cacheControl:"300",upsert:true});if(up)throw up;const {data:signed,error:se}=await db.storage.from("exports").createSignedUrl(path,600);if(se)throw se;return json({ok:true,url:signed?.signedUrl||null,count:ordered.length,total:ordered.reduce((s:number,e:any)=>s+Number(e.amount||0),0),filename:`ADMA_компенсация_${stamp}.pdf`})}catch(e){const m=e instanceof Error?e.message:"unknown_error";return json({error:m},e instanceof AuthError?e.status:["missing_hash","bad_signature","expired_init_data","missing_user"].includes(m)?401:500)}});

